### ISSUE TITLE
一对多及引用类型的维护和查询

### ISSUE THREAD

**Issue by AdamvvYau** [China-Mr-zhong/Fast-Framework#2]
未见到有一对多和引用类型的维护和查询的介绍，有这部分功能吗？还是需要自行实现？

**Comment by China-Mr-zhong** [comment]
你好，很高兴你能提出问题，目前是可以使用 Include查询 实现 一对一 或一对多查询，但文档未做相关用法说明，因为我觉得这块还有一些优化空间，后续完善功能以及说明文档。

**Comment by China-Mr-zhong** [comment]
Include 已做了相关代码优化，可查阅最新代码以及文档
